"""Route for on-demand rendering of already-generated diagram source."""
from flask import Blueprint, request

from services import dot_to_svg
from utils import ResponseBuilder
from .utils import compact_for_log, log_to_csv

render_bp = Blueprint('render', __name__)

@render_bp.route('/api/render-dot-svg', methods=['POST'])
def render_dot_svg():
    """Render DOT source (already generated by a previous /api/generate-* call) to SVG."""
    data = request.get_json()
    dot_content = data.get('dot', '')

    client_ip = request.remote_addr
    route = request.path
    log_to_csv(client_ip, route, f"dot={compact_for_log(dot_content)}")

    if not dot_content or not dot_content.strip():
        return ResponseBuilder.validation_error("dot", "DOT content cannot be empty.")

    svg = dot_to_svg(dot_content)
    if svg is None:
        return ResponseBuilder.error(
            "dot -Tsvg conversion failed (is graphviz installed?).",
            status_code=500
        )

    return ResponseBuilder.success(data={"svg": svg})